/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class COMAKSecondaryCoordinate extends OpenSimObject {
  private transient long swigCPtr;

  public COMAKSecondaryCoordinate(long cPtr, boolean cMemoryOwn) {
    super(opensimJAMJNI.COMAKSecondaryCoordinate_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(COMAKSecondaryCoordinate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimJAMJNI.delete_COMAKSecondaryCoordinate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static COMAKSecondaryCoordinate safeDownCast(OpenSimObject obj) {
    long cPtr = opensimJAMJNI.COMAKSecondaryCoordinate_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new COMAKSecondaryCoordinate(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimJAMJNI.COMAKSecondaryCoordinate_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimJAMJNI.COMAKSecondaryCoordinate_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimJAMJNI.COMAKSecondaryCoordinate_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new COMAKSecondaryCoordinate(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimJAMJNI.COMAKSecondaryCoordinate_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_coordinate(COMAKSecondaryCoordinate source) {
    opensimJAMJNI.COMAKSecondaryCoordinate_copyProperty_coordinate(swigCPtr, this, COMAKSecondaryCoordinate.getCPtr(source), source);
  }

  public String get_coordinate(int i) {
    return opensimJAMJNI.COMAKSecondaryCoordinate_get_coordinate__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_coordinate(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.COMAKSecondaryCoordinate_upd_coordinate__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_coordinate(int i, String value) {
    opensimJAMJNI.COMAKSecondaryCoordinate_set_coordinate__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_coordinate(String value) {
    return opensimJAMJNI.COMAKSecondaryCoordinate_append_coordinate(swigCPtr, this, value);
  }

  public void constructProperty_coordinate(String initValue) {
    opensimJAMJNI.COMAKSecondaryCoordinate_constructProperty_coordinate(swigCPtr, this, initValue);
  }

  public String get_coordinate() {
    return opensimJAMJNI.COMAKSecondaryCoordinate_get_coordinate__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_coordinate() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.COMAKSecondaryCoordinate_upd_coordinate__SWIG_1(swigCPtr, this), false);
  }

  public void set_coordinate(String value) {
    opensimJAMJNI.COMAKSecondaryCoordinate_set_coordinate__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_max_change(COMAKSecondaryCoordinate source) {
    opensimJAMJNI.COMAKSecondaryCoordinate_copyProperty_max_change(swigCPtr, this, COMAKSecondaryCoordinate.getCPtr(source), source);
  }

  public double get_max_change(int i) {
    return opensimJAMJNI.COMAKSecondaryCoordinate_get_max_change__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_max_change(int i) {
    return new SWIGTYPE_p_double(opensimJAMJNI.COMAKSecondaryCoordinate_upd_max_change__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_max_change(int i, double value) {
    opensimJAMJNI.COMAKSecondaryCoordinate_set_max_change__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_max_change(double value) {
    return opensimJAMJNI.COMAKSecondaryCoordinate_append_max_change(swigCPtr, this, value);
  }

  public void constructProperty_max_change(double initValue) {
    opensimJAMJNI.COMAKSecondaryCoordinate_constructProperty_max_change(swigCPtr, this, initValue);
  }

  public double get_max_change() {
    return opensimJAMJNI.COMAKSecondaryCoordinate_get_max_change__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_max_change() {
    return new SWIGTYPE_p_double(opensimJAMJNI.COMAKSecondaryCoordinate_upd_max_change__SWIG_1(swigCPtr, this), false);
  }

  public void set_max_change(double value) {
    opensimJAMJNI.COMAKSecondaryCoordinate_set_max_change__SWIG_1(swigCPtr, this, value);
  }

  public COMAKSecondaryCoordinate() {
    this(opensimJAMJNI.new_COMAKSecondaryCoordinate(), true);
  }

  public void constructProperties() {
    opensimJAMJNI.COMAKSecondaryCoordinate_constructProperties(swigCPtr, this);
  }

}
