/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class COMAKCostFunctionParameterSet extends SetCOMAKCostFunctionParameters {
  private transient long swigCPtr;

  public COMAKCostFunctionParameterSet(long cPtr, boolean cMemoryOwn) {
    super(opensimJAMJNI.COMAKCostFunctionParameterSet_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(COMAKCostFunctionParameterSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimJAMJNI.delete_COMAKCostFunctionParameterSet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static COMAKCostFunctionParameterSet safeDownCast(OpenSimObject obj) {
    long cPtr = opensimJAMJNI.COMAKCostFunctionParameterSet_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new COMAKCostFunctionParameterSet(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimJAMJNI.COMAKCostFunctionParameterSet_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimJAMJNI.COMAKCostFunctionParameterSet_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimJAMJNI.COMAKCostFunctionParameterSet_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new COMAKCostFunctionParameterSet(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimJAMJNI.COMAKCostFunctionParameterSet_getConcreteClassName(swigCPtr, this);
  }

  public COMAKCostFunctionParameterSet() {
    this(opensimJAMJNI.new_COMAKCostFunctionParameterSet(), true);
  }

  public void constructProperties() {
    opensimJAMJNI.COMAKCostFunctionParameterSet_constructProperties(swigCPtr, this);
  }

}
