/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class COMAKSecondaryCoordinateSet extends SetCOMAKSecondaryCoordinates {
  private transient long swigCPtr;

  public COMAKSecondaryCoordinateSet(long cPtr, boolean cMemoryOwn) {
    super(opensimJAMJNI.COMAKSecondaryCoordinateSet_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(COMAKSecondaryCoordinateSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimJAMJNI.delete_COMAKSecondaryCoordinateSet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static COMAKSecondaryCoordinateSet safeDownCast(OpenSimObject obj) {
    long cPtr = opensimJAMJNI.COMAKSecondaryCoordinateSet_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new COMAKSecondaryCoordinateSet(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimJAMJNI.COMAKSecondaryCoordinateSet_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimJAMJNI.COMAKSecondaryCoordinateSet_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimJAMJNI.COMAKSecondaryCoordinateSet_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new COMAKSecondaryCoordinateSet(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimJAMJNI.COMAKSecondaryCoordinateSet_getConcreteClassName(swigCPtr, this);
  }

  public COMAKSecondaryCoordinateSet() {
    this(opensimJAMJNI.new_COMAKSecondaryCoordinateSet(), true);
  }

}
