/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

/**
 * The JointMechanicsTool enables detailed analyses of simulation results and the <br>
 * generation of output files for visualization outside the OpenSim GUI and <br>
 * further analyses in MATLAB/Python. To use this tool, a simulation must be <br>
 * performed (using a different tool) with the model states written to a .sto file.<br>
 * The JointMechanicsTool reposes the model at the states listed in the <br>
 * states_file and performs further analyses. <br>
 * <br>
 * A key feature of the JointMechanicsTool is the ability to write .vtp files <br>
 * for each timestep that contain both geometric information (vertex locations <br>
 * and connectivity) and simulations outputs. These .vtp <br>
 * files can then be read into a visualization software such as Paraview to <br>
 * generate high quality renderings of simulation results. This feature is <br>
 * especially useful for models with Smith2018ArticularContact Components because <br>
 * it enables triangle level outputs (proximity, pressure, potential energy, etc).<br>
 * to visualized on the mesh geometry. Muscle and Blankevoort1991Ligament <br>
 * components can also be written as .vtp files such that they can be colored<br>
 * by their output values in visualizations. Finally, AttachedGeometry meshes <br>
 * (ie bones) can also be written as .vtp files for visualiation. The model<br>
 * components and respective outputs that are written to .vtp files can be<br>
 * controlled using the contacts, contact_outputs, ligaments, ligament_ouputs, <br>
 * muscles, muscle_outputs, and attached_geometry_bodies properties. 
 */
public class JointMechanicsTool extends OpenSimObject {
  private transient long swigCPtr;

  public JointMechanicsTool(long cPtr, boolean cMemoryOwn) {
    super(opensimJAMJNI.JointMechanicsTool_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(JointMechanicsTool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimJAMJNI.delete_JointMechanicsTool(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static JointMechanicsTool safeDownCast(OpenSimObject obj) {
    long cPtr = opensimJAMJNI.JointMechanicsTool_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new JointMechanicsTool(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimJAMJNI.JointMechanicsTool_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimJAMJNI.JointMechanicsTool_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimJAMJNI.JointMechanicsTool_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new JointMechanicsTool(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimJAMJNI.JointMechanicsTool_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_model_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_model_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_model_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_model_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_model_file(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_model_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_model_file(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_model_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_model_file(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_model_file(swigCPtr, this, value);
  }

  public void constructProperty_model_file(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_model_file(swigCPtr, this, initValue);
  }

  public String get_model_file() {
    return opensimJAMJNI.JointMechanicsTool_get_model_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_model_file() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_model_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_model_file(String value) {
    opensimJAMJNI.JointMechanicsTool_set_model_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_input_states_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_input_states_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_input_states_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_input_states_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_input_states_file(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_states_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_input_states_file(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_states_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_input_states_file(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_input_states_file(swigCPtr, this, value);
  }

  public void constructProperty_input_states_file(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_input_states_file(swigCPtr, this, initValue);
  }

  public String get_input_states_file() {
    return opensimJAMJNI.JointMechanicsTool_get_input_states_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_input_states_file() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_states_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_input_states_file(String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_states_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_use_muscle_physiology(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_use_muscle_physiology(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_use_muscle_physiology(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_use_muscle_physiology__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_use_muscle_physiology(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_use_muscle_physiology__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_use_muscle_physiology(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_use_muscle_physiology__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_use_muscle_physiology(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_use_muscle_physiology(swigCPtr, this, value);
  }

  public void constructProperty_use_muscle_physiology(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_use_muscle_physiology(swigCPtr, this, initValue);
  }

  public boolean get_use_muscle_physiology() {
    return opensimJAMJNI.JointMechanicsTool_get_use_muscle_physiology__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_use_muscle_physiology() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_use_muscle_physiology__SWIG_1(swigCPtr, this), false);
  }

  public void set_use_muscle_physiology(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_use_muscle_physiology__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_input_transforms_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_input_transforms_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_input_transforms_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_input_transforms_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_input_transforms_file(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_transforms_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_input_transforms_file(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_transforms_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_input_transforms_file(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_input_transforms_file(swigCPtr, this, value);
  }

  public void constructProperty_input_transforms_file(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_input_transforms_file(swigCPtr, this, initValue);
  }

  public String get_input_transforms_file() {
    return opensimJAMJNI.JointMechanicsTool_get_input_transforms_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_input_transforms_file() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_transforms_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_input_transforms_file(String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_transforms_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_input_forces_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_input_forces_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_input_forces_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_input_forces_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_input_forces_file(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_forces_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_input_forces_file(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_forces_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_input_forces_file(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_input_forces_file(swigCPtr, this, value);
  }

  public void constructProperty_input_forces_file(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_input_forces_file(swigCPtr, this, initValue);
  }

  public String get_input_forces_file() {
    return opensimJAMJNI.JointMechanicsTool_get_input_forces_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_input_forces_file() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_input_forces_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_input_forces_file(String value) {
    opensimJAMJNI.JointMechanicsTool_set_input_forces_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_results_directory(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_results_directory(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_results_directory(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_results_directory__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_results_directory(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_results_directory__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_results_directory(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_results_directory__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_results_directory(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_results_directory(swigCPtr, this, value);
  }

  public void constructProperty_results_directory(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_results_directory(swigCPtr, this, initValue);
  }

  public String get_results_directory() {
    return opensimJAMJNI.JointMechanicsTool_get_results_directory__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_results_directory() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_results_directory__SWIG_1(swigCPtr, this), false);
  }

  public void set_results_directory(String value) {
    opensimJAMJNI.JointMechanicsTool_set_results_directory__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_results_file_basename(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_results_file_basename(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_results_file_basename(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_results_file_basename__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_results_file_basename(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_results_file_basename__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_results_file_basename(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_results_file_basename__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_results_file_basename(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_results_file_basename(swigCPtr, this, value);
  }

  public void constructProperty_results_file_basename(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_results_file_basename(swigCPtr, this, initValue);
  }

  public String get_results_file_basename() {
    return opensimJAMJNI.JointMechanicsTool_get_results_file_basename__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_results_file_basename() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_results_file_basename__SWIG_1(swigCPtr, this), false);
  }

  public void set_results_file_basename(String value) {
    opensimJAMJNI.JointMechanicsTool_set_results_file_basename__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_start_time(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_start_time(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public double get_start_time(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_start_time__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_start_time(int i) {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_start_time__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_start_time(int i, double value) {
    opensimJAMJNI.JointMechanicsTool_set_start_time__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_start_time(double value) {
    return opensimJAMJNI.JointMechanicsTool_append_start_time(swigCPtr, this, value);
  }

  public void constructProperty_start_time(double initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_start_time(swigCPtr, this, initValue);
  }

  public double get_start_time() {
    return opensimJAMJNI.JointMechanicsTool_get_start_time__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_start_time() {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_start_time__SWIG_1(swigCPtr, this), false);
  }

  public void set_start_time(double value) {
    opensimJAMJNI.JointMechanicsTool_set_start_time__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_stop_time(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_stop_time(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public double get_stop_time(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_stop_time__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_stop_time(int i) {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_stop_time__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_stop_time(int i, double value) {
    opensimJAMJNI.JointMechanicsTool_set_stop_time__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_stop_time(double value) {
    return opensimJAMJNI.JointMechanicsTool_append_stop_time(swigCPtr, this, value);
  }

  public void constructProperty_stop_time(double initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_stop_time(swigCPtr, this, initValue);
  }

  public double get_stop_time() {
    return opensimJAMJNI.JointMechanicsTool_get_stop_time__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_stop_time() {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_stop_time__SWIG_1(swigCPtr, this), false);
  }

  public void set_stop_time(double value) {
    opensimJAMJNI.JointMechanicsTool_set_stop_time__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_resample_step_size(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_resample_step_size(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public double get_resample_step_size(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_resample_step_size__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_resample_step_size(int i) {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_resample_step_size__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_resample_step_size(int i, double value) {
    opensimJAMJNI.JointMechanicsTool_set_resample_step_size__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_resample_step_size(double value) {
    return opensimJAMJNI.JointMechanicsTool_append_resample_step_size(swigCPtr, this, value);
  }

  public void constructProperty_resample_step_size(double initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_resample_step_size(swigCPtr, this, initValue);
  }

  public double get_resample_step_size() {
    return opensimJAMJNI.JointMechanicsTool_get_resample_step_size__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_resample_step_size() {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_resample_step_size__SWIG_1(swigCPtr, this), false);
  }

  public void set_resample_step_size(double value) {
    opensimJAMJNI.JointMechanicsTool_set_resample_step_size__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_normalize_to_cycle(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_normalize_to_cycle(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_normalize_to_cycle(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_normalize_to_cycle__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_normalize_to_cycle(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_normalize_to_cycle__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_normalize_to_cycle(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_normalize_to_cycle__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_normalize_to_cycle(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_normalize_to_cycle(swigCPtr, this, value);
  }

  public void constructProperty_normalize_to_cycle(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_normalize_to_cycle(swigCPtr, this, initValue);
  }

  public boolean get_normalize_to_cycle() {
    return opensimJAMJNI.JointMechanicsTool_get_normalize_to_cycle__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_normalize_to_cycle() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_normalize_to_cycle__SWIG_1(swigCPtr, this), false);
  }

  public void set_normalize_to_cycle(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_normalize_to_cycle__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_lowpass_filter_frequency(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_lowpass_filter_frequency(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public double get_lowpass_filter_frequency(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_lowpass_filter_frequency__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_lowpass_filter_frequency(int i) {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_lowpass_filter_frequency__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_lowpass_filter_frequency(int i, double value) {
    opensimJAMJNI.JointMechanicsTool_set_lowpass_filter_frequency__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_lowpass_filter_frequency(double value) {
    return opensimJAMJNI.JointMechanicsTool_append_lowpass_filter_frequency(swigCPtr, this, value);
  }

  public void constructProperty_lowpass_filter_frequency(double initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_lowpass_filter_frequency(swigCPtr, this, initValue);
  }

  public double get_lowpass_filter_frequency() {
    return opensimJAMJNI.JointMechanicsTool_get_lowpass_filter_frequency__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_lowpass_filter_frequency() {
    return new SWIGTYPE_p_double(opensimJAMJNI.JointMechanicsTool_upd_lowpass_filter_frequency__SWIG_1(swigCPtr, this), false);
  }

  public void set_lowpass_filter_frequency(double value) {
    opensimJAMJNI.JointMechanicsTool_set_lowpass_filter_frequency__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_print_processed_kinematics(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_print_processed_kinematics(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_print_processed_kinematics(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_print_processed_kinematics__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_print_processed_kinematics(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_print_processed_kinematics__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_print_processed_kinematics(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_print_processed_kinematics__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_print_processed_kinematics(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_print_processed_kinematics(swigCPtr, this, value);
  }

  public void constructProperty_print_processed_kinematics(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_print_processed_kinematics(swigCPtr, this, initValue);
  }

  public boolean get_print_processed_kinematics() {
    return opensimJAMJNI.JointMechanicsTool_get_print_processed_kinematics__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_print_processed_kinematics() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_print_processed_kinematics__SWIG_1(swigCPtr, this), false);
  }

  public void set_print_processed_kinematics(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_print_processed_kinematics__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_contacts(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_contacts(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_contacts(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_contacts(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_contacts(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_contacts(swigCPtr, this, i), false);
  }

  public void set_contacts(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_contacts(swigCPtr, this, i, value);
  }

  public int append_contacts(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_contacts(swigCPtr, this, value);
  }

  public void constructProperty_contacts() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_contacts(swigCPtr, this);
  }

  public void copyProperty_contact_outputs(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_contact_outputs(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_contact_outputs(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_contact_outputs(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_contact_outputs(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_contact_outputs(swigCPtr, this, i), false);
  }

  public void set_contact_outputs(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_contact_outputs(swigCPtr, this, i, value);
  }

  public int append_contact_outputs(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_contact_outputs(swigCPtr, this, value);
  }

  public void constructProperty_contact_outputs() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_contact_outputs(swigCPtr, this);
  }

  public void copyProperty_contact_mesh_properties(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_contact_mesh_properties(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_contact_mesh_properties(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_contact_mesh_properties(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_contact_mesh_properties(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_contact_mesh_properties(swigCPtr, this, i), false);
  }

  public void set_contact_mesh_properties(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_contact_mesh_properties(swigCPtr, this, i, value);
  }

  public int append_contact_mesh_properties(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_contact_mesh_properties(swigCPtr, this, value);
  }

  public void constructProperty_contact_mesh_properties() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_contact_mesh_properties(swigCPtr, this);
  }

  public void copyProperty_ligaments(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_ligaments(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_ligaments(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_ligaments(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_ligaments(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_ligaments(swigCPtr, this, i), false);
  }

  public void set_ligaments(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_ligaments(swigCPtr, this, i, value);
  }

  public int append_ligaments(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_ligaments(swigCPtr, this, value);
  }

  public void constructProperty_ligaments() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_ligaments(swigCPtr, this);
  }

  public void copyProperty_ligament_outputs(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_ligament_outputs(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_ligament_outputs(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_ligament_outputs(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_ligament_outputs(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_ligament_outputs(swigCPtr, this, i), false);
  }

  public void set_ligament_outputs(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_ligament_outputs(swigCPtr, this, i, value);
  }

  public int append_ligament_outputs(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_ligament_outputs(swigCPtr, this, value);
  }

  public void constructProperty_ligament_outputs() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_ligament_outputs(swigCPtr, this);
  }

  public void copyProperty_muscles(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_muscles(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_muscles(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_muscles(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_muscles(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_muscles(swigCPtr, this, i), false);
  }

  public void set_muscles(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_muscles(swigCPtr, this, i, value);
  }

  public int append_muscles(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_muscles(swigCPtr, this, value);
  }

  public void constructProperty_muscles() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_muscles(swigCPtr, this);
  }

  public void copyProperty_muscle_outputs(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_muscle_outputs(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_muscle_outputs(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_muscle_outputs(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_muscle_outputs(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_muscle_outputs(swigCPtr, this, i), false);
  }

  public void set_muscle_outputs(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_muscle_outputs(swigCPtr, this, i, value);
  }

  public int append_muscle_outputs(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_muscle_outputs(swigCPtr, this, value);
  }

  public void constructProperty_muscle_outputs() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_muscle_outputs(swigCPtr, this);
  }

  public void copyProperty_attached_geometry_bodies(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_attached_geometry_bodies(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_attached_geometry_bodies(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_attached_geometry_bodies(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_attached_geometry_bodies(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_attached_geometry_bodies(swigCPtr, this, i), false);
  }

  public void set_attached_geometry_bodies(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_attached_geometry_bodies(swigCPtr, this, i, value);
  }

  public int append_attached_geometry_bodies(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_attached_geometry_bodies(swigCPtr, this, value);
  }

  public void constructProperty_attached_geometry_bodies() {
    opensimJAMJNI.JointMechanicsTool_constructProperty_attached_geometry_bodies(swigCPtr, this);
  }

  public void copyProperty_output_position_frame(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_output_position_frame(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_output_position_frame(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_output_position_frame__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_output_position_frame(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_position_frame__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_output_position_frame(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_position_frame__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_output_position_frame(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_output_position_frame(swigCPtr, this, value);
  }

  public void constructProperty_output_position_frame(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_output_position_frame(swigCPtr, this, initValue);
  }

  public String get_output_position_frame() {
    return opensimJAMJNI.JointMechanicsTool_get_output_position_frame__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_output_position_frame() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_position_frame__SWIG_1(swigCPtr, this), false);
  }

  public void set_output_position_frame(String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_position_frame__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_output_orientation_frame(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_output_orientation_frame(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_output_orientation_frame(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_output_orientation_frame__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_output_orientation_frame(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_orientation_frame__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_output_orientation_frame(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_orientation_frame__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_output_orientation_frame(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_output_orientation_frame(swigCPtr, this, value);
  }

  public void constructProperty_output_orientation_frame(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_output_orientation_frame(swigCPtr, this, initValue);
  }

  public String get_output_orientation_frame() {
    return opensimJAMJNI.JointMechanicsTool_get_output_orientation_frame__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_output_orientation_frame() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_orientation_frame__SWIG_1(swigCPtr, this), false);
  }

  public void set_output_orientation_frame(String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_orientation_frame__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_write_vtp_files(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_write_vtp_files(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_write_vtp_files(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_write_vtp_files__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_write_vtp_files(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_vtp_files__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_write_vtp_files(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_vtp_files__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_write_vtp_files(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_write_vtp_files(swigCPtr, this, value);
  }

  public void constructProperty_write_vtp_files(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_write_vtp_files(swigCPtr, this, initValue);
  }

  public boolean get_write_vtp_files() {
    return opensimJAMJNI.JointMechanicsTool_get_write_vtp_files__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_write_vtp_files() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_vtp_files__SWIG_1(swigCPtr, this), false);
  }

  public void set_write_vtp_files(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_vtp_files__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_vtp_file_format(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_vtp_file_format(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_vtp_file_format(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_vtp_file_format__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_vtp_file_format(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_vtp_file_format__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_vtp_file_format(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_vtp_file_format__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_vtp_file_format(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_vtp_file_format(swigCPtr, this, value);
  }

  public void constructProperty_vtp_file_format(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_vtp_file_format(swigCPtr, this, initValue);
  }

  public String get_vtp_file_format() {
    return opensimJAMJNI.JointMechanicsTool_get_vtp_file_format__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_vtp_file_format() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_vtp_file_format__SWIG_1(swigCPtr, this), false);
  }

  public void set_vtp_file_format(String value) {
    opensimJAMJNI.JointMechanicsTool_set_vtp_file_format__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_write_h5_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_write_h5_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_write_h5_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_write_h5_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_write_h5_file(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_h5_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_write_h5_file(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_h5_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_write_h5_file(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_write_h5_file(swigCPtr, this, value);
  }

  public void constructProperty_write_h5_file(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_write_h5_file(swigCPtr, this, initValue);
  }

  public boolean get_write_h5_file() {
    return opensimJAMJNI.JointMechanicsTool_get_write_h5_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_write_h5_file() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_h5_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_write_h5_file(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_h5_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_h5_states_data(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_h5_states_data(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_h5_states_data(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_h5_states_data__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_h5_states_data(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_h5_states_data__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_h5_states_data(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_h5_states_data__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_h5_states_data(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_h5_states_data(swigCPtr, this, value);
  }

  public void constructProperty_h5_states_data(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_h5_states_data(swigCPtr, this, initValue);
  }

  public boolean get_h5_states_data() {
    return opensimJAMJNI.JointMechanicsTool_get_h5_states_data__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_h5_states_data() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_h5_states_data__SWIG_1(swigCPtr, this), false);
  }

  public void set_h5_states_data(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_h5_states_data__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_h5_kinematics_data(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_h5_kinematics_data(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_h5_kinematics_data(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_h5_kinematics_data__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_h5_kinematics_data(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_h5_kinematics_data__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_h5_kinematics_data(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_h5_kinematics_data__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_h5_kinematics_data(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_h5_kinematics_data(swigCPtr, this, value);
  }

  public void constructProperty_h5_kinematics_data(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_h5_kinematics_data(swigCPtr, this, initValue);
  }

  public boolean get_h5_kinematics_data() {
    return opensimJAMJNI.JointMechanicsTool_get_h5_kinematics_data__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_h5_kinematics_data() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_h5_kinematics_data__SWIG_1(swigCPtr, this), false);
  }

  public void set_h5_kinematics_data(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_h5_kinematics_data__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_AnalysisSet(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_AnalysisSet(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public AnalysisSet get_AnalysisSet(int i) {
    return new AnalysisSet(opensimJAMJNI.JointMechanicsTool_get_AnalysisSet__SWIG_0(swigCPtr, this, i), false);
  }

  public AnalysisSet upd_AnalysisSet(int i) {
    return new AnalysisSet(opensimJAMJNI.JointMechanicsTool_upd_AnalysisSet__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_AnalysisSet(int i, AnalysisSet value) {
    opensimJAMJNI.JointMechanicsTool_set_AnalysisSet__SWIG_0(swigCPtr, this, i, AnalysisSet.getCPtr(value), value);
  }

  public int append_AnalysisSet(AnalysisSet value) {
    return opensimJAMJNI.JointMechanicsTool_append_AnalysisSet(swigCPtr, this, AnalysisSet.getCPtr(value), value);
  }

  public void constructProperty_AnalysisSet(AnalysisSet initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_AnalysisSet(swigCPtr, this, AnalysisSet.getCPtr(initValue), initValue);
  }

  public AnalysisSet get_AnalysisSet() {
    return new AnalysisSet(opensimJAMJNI.JointMechanicsTool_get_AnalysisSet__SWIG_1(swigCPtr, this), false);
  }

  public AnalysisSet upd_AnalysisSet() {
    return new AnalysisSet(opensimJAMJNI.JointMechanicsTool_upd_AnalysisSet__SWIG_1(swigCPtr, this), false);
  }

  public void set_AnalysisSet(AnalysisSet value) {
    opensimJAMJNI.JointMechanicsTool_set_AnalysisSet__SWIG_1(swigCPtr, this, AnalysisSet.getCPtr(value), value);
  }

  public void copyProperty_write_transforms_file(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_write_transforms_file(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_write_transforms_file(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_write_transforms_file__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_write_transforms_file(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_transforms_file__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_write_transforms_file(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_transforms_file__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_write_transforms_file(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_write_transforms_file(swigCPtr, this, value);
  }

  public void constructProperty_write_transforms_file(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_write_transforms_file(swigCPtr, this, initValue);
  }

  public boolean get_write_transforms_file() {
    return opensimJAMJNI.JointMechanicsTool_get_write_transforms_file__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_write_transforms_file() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_write_transforms_file__SWIG_1(swigCPtr, this), false);
  }

  public void set_write_transforms_file(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_write_transforms_file__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_output_transforms_file_type(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_output_transforms_file_type(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public String get_output_transforms_file_type(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_output_transforms_file_type__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_output_transforms_file_type(int i) {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_transforms_file_type__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_output_transforms_file_type(int i, String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_transforms_file_type__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_output_transforms_file_type(String value) {
    return opensimJAMJNI.JointMechanicsTool_append_output_transforms_file_type(swigCPtr, this, value);
  }

  public void constructProperty_output_transforms_file_type(String initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_output_transforms_file_type(swigCPtr, this, initValue);
  }

  public String get_output_transforms_file_type() {
    return opensimJAMJNI.JointMechanicsTool_get_output_transforms_file_type__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_output_transforms_file_type() {
    return new SWIGTYPE_p_std__string(opensimJAMJNI.JointMechanicsTool_upd_output_transforms_file_type__SWIG_1(swigCPtr, this), false);
  }

  public void set_output_transforms_file_type(String value) {
    opensimJAMJNI.JointMechanicsTool_set_output_transforms_file_type__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_use_visualizer(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_use_visualizer(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public boolean get_use_visualizer(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_use_visualizer__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_use_visualizer(int i) {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_use_visualizer__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_use_visualizer(int i, boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_use_visualizer__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_use_visualizer(boolean value) {
    return opensimJAMJNI.JointMechanicsTool_append_use_visualizer(swigCPtr, this, value);
  }

  public void constructProperty_use_visualizer(boolean initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_use_visualizer(swigCPtr, this, initValue);
  }

  public boolean get_use_visualizer() {
    return opensimJAMJNI.JointMechanicsTool_get_use_visualizer__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_use_visualizer() {
    return new SWIGTYPE_p_bool(opensimJAMJNI.JointMechanicsTool_upd_use_visualizer__SWIG_1(swigCPtr, this), false);
  }

  public void set_use_visualizer(boolean value) {
    opensimJAMJNI.JointMechanicsTool_set_use_visualizer__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_verbose(JointMechanicsTool source) {
    opensimJAMJNI.JointMechanicsTool_copyProperty_verbose(swigCPtr, this, JointMechanicsTool.getCPtr(source), source);
  }

  public int get_verbose(int i) {
    return opensimJAMJNI.JointMechanicsTool_get_verbose__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_int upd_verbose(int i) {
    return new SWIGTYPE_p_int(opensimJAMJNI.JointMechanicsTool_upd_verbose__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_verbose(int i, int value) {
    opensimJAMJNI.JointMechanicsTool_set_verbose__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_verbose(int value) {
    return opensimJAMJNI.JointMechanicsTool_append_verbose(swigCPtr, this, value);
  }

  public void constructProperty_verbose(int initValue) {
    opensimJAMJNI.JointMechanicsTool_constructProperty_verbose(swigCPtr, this, initValue);
  }

  public int get_verbose() {
    return opensimJAMJNI.JointMechanicsTool_get_verbose__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_int upd_verbose() {
    return new SWIGTYPE_p_int(opensimJAMJNI.JointMechanicsTool_upd_verbose__SWIG_1(swigCPtr, this), false);
  }

  public void set_verbose(int value) {
    opensimJAMJNI.JointMechanicsTool_set_verbose__SWIG_1(swigCPtr, this, value);
  }

  public JointMechanicsTool() {
    this(opensimJAMJNI.new_JointMechanicsTool__SWIG_0(), true);
  }

  public JointMechanicsTool(String settings_file) {
    this(opensimJAMJNI.new_JointMechanicsTool__SWIG_1(settings_file), true);
  }

  public void setModel(Model aModel) {
    opensimJAMJNI.JointMechanicsTool_setModel(swigCPtr, this, Model.getCPtr(aModel), aModel);
  }

  public boolean run() {
    return opensimJAMJNI.JointMechanicsTool_run(swigCPtr, this);
  }

  public int printResults(String aBaseName, String aDir) {
    return opensimJAMJNI.JointMechanicsTool_printResults(swigCPtr, this, aBaseName, aDir);
  }

}
