/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class opensimJAM {
  public static String GetJAMVersionAndDate() {
    return opensimJAMJNI.GetJAMVersionAndDate();
  }

  public static String GetJAMVersion() {
    return opensimJAMJNI.GetJAMVersion();
  }

}
