/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class VTPFileAdapter extends FileAdapter {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected VTPFileAdapter(long cPtr, boolean cMemoryOwn) {
    super(opensimJAMJNI.VTPFileAdapter_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VTPFileAdapter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        opensimJAMJNI.delete_VTPFileAdapter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public VTPFileAdapter() {
    this(opensimJAMJNI.new_VTPFileAdapter__SWIG_0(), true);
  }

  public VTPFileAdapter(VTPFileAdapter arg0) {
    this(opensimJAMJNI.new_VTPFileAdapter__SWIG_1(VTPFileAdapter.getCPtr(arg0), arg0), true);
  }

  public DataAdapter clone() {
    long cPtr = opensimJAMJNI.VTPFileAdapter_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new VTPFileAdapter(cPtr, true);
  }

  /**
   *        <br>
   * <br>
   *         
   */
  public void write(String fileName, String filePath, int frame_num) {
    opensimJAMJNI.VTPFileAdapter_write(swigCPtr, this, fileName, filePath, frame_num);
  }

  /**
   *        <br>
   * <br>
   *        @param aFaceData<br>
   *             A vector [nDataField] of SimTK::Matrix [nTimeStep x nFaces]<br>
   *             containing data values for each face in the contact mesh<br>
   *        
   */
  public void appendFaceData(String aFaceDataName, Vector aFaceData) {
    opensimJAMJNI.VTPFileAdapter_appendFaceData(swigCPtr, this, aFaceDataName, Vector.getCPtr(aFaceData), aFaceData);
  }

  public void appendPointData(String aPointDataNames, Vector aPointData) {
    opensimJAMJNI.VTPFileAdapter_appendPointData(swigCPtr, this, aPointDataNames, Vector.getCPtr(aPointData), aPointData);
  }

  public void setDataFormat(SWIGTYPE_p_SimTK__String format) {
    opensimJAMJNI.VTPFileAdapter_setDataFormat(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(format));
  }

  public void setPointLocations(RowVectorVec3 vertices) {
    opensimJAMJNI.VTPFileAdapter_setPointLocations(swigCPtr, this, RowVectorVec3.getCPtr(vertices), vertices);
  }

  public void setPolygonConnectivity(Matrix faces) {
    opensimJAMJNI.VTPFileAdapter_setPolygonConnectivity(swigCPtr, this, Matrix.getCPtr(faces), faces);
  }

  public void setPolygonsFromMesh(PolygonalMesh mesh) {
    opensimJAMJNI.VTPFileAdapter_setPolygonsFromMesh(swigCPtr, this, PolygonalMesh.getCPtr(mesh), mesh);
  }

  public void setLineConnectivity(Vector line) {
    opensimJAMJNI.VTPFileAdapter_setLineConnectivity(swigCPtr, this, Vector.getCPtr(line), line);
  }

}
